Feature/music service
AntonZhidovich/MusicStreamingApp pull request #2
Opened 2024-02-15 22:08 UTC by AntonZhidovich

Music service on clean architecture for working with playlists, track playback and viewing its information

MS SQL Server for storing information about authors, releases and songs.
MongoDB for storing user playlists and tariff plan constraints.
MinIO for storing soundtracks.

2024-02-28 20:38 UTC, katyalys requested changes

2024-02-28 20:38 UTC, katyalys commented on MusicService/MusicService.API/Controllers/GenreController.cs
> +        public async Task<IActionResult> GetAllGenresAsync([FromQuery] GetPageRequest request)
why do you use "" in HttpGet?

2024-02-28 20:38 UTC, katyalys commented on MusicService/MusicService.Application/Mapping/AuthorMappingProfile.cs
> +            CreateMap<CreateAuthorRequest, Author>()
same as in previous pr

2024-02-28 20:38 UTC, katyalys commented on MusicService/MusicService.Application/Services/AuthorService.cs
> +            if (!currentUser.IsInRole(UserRoles.admin)) { CheckIfUserIsMember(author, currentUser); }
move to new line CheckIfUserIsMember(author, currentUser);

2024-02-28 20:38 UTC, katyalys commented on MusicService/MusicService.Application/Services/AuthorService.cs
> +            if (!currentUser.IsInRole(UserRoles.admin)) { CheckIfUserIsMember(author, currentUser); }
new line for CheckIfUserIsMember(author, currentUser);

2024-02-28 20:38 UTC, katyalys commented on MusicService/MusicService.Application/Services/ReleaseService.cs
> +            {
i guess you can use Any() instead of loop

2024-02-29 07:35 UTC, AntonZhidovich commented on MusicService/MusicService.API/Controllers/GenreController.cs
> +        public async Task<IActionResult> GetAllGenresAsync([FromQuery] GetPageRequest request)
removed

2024-03-01 14:07 UTC, katyalys approved these changes

2024-03-03 15:22 UTC, merged